# Generated by Django 4.1.7 on 2023-04-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_stall_availability_stall_stall_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='stall_state',
            new_name='stall_availability',
        ),
    ]
