# Generated by Django 4.1.7 on 2023-03-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('referenceKey', models.CharField(default='', max_length=30)),
                ('passWord', models.CharField(default='', max_length=30)),
                ('gcashLink', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
