# Generated by Django 4.1.7 on 2023-03-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=30)),
                ('item_desc', models.TextField(default='', max_length=255)),
                ('item_cost', models.IntegerField(default=0)),
                ('vendorOwner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vendorpage.vendor')),
            ],
        ),
    ]
