# Generated by Django 4.1.7 on 2023-03-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpage', '0002_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='item_avail',
            field=models.BooleanField(default=False),
        ),
    ]
