# Generated by Django 4.1.7 on 2023-03-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpage', '0003_food_item_item_avail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='vendor_name',
        ),
    ]
