# Generated by Django 4.1.7 on 2023-03-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpage', '0004_rename_name_vendor_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
