# Generated by Django 4.1.7 on 2023-04-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpage', '0006_remove_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_desc', models.CharField(default='', max_length=255)),
                ('stall_availability', models.BooleanField(default=True)),
                ('stall_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('stall_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorpage.vendor')),
            ],
        ),
    ]
