# Generated by Django 4.2 on 2023-04-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendorpage', '0007_vendorprofile'),
        ('orderpage', '0002_item_order_delete_orderbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorpage.food_item'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorpage.vendor'),
        ),
    ]
